services:
  # POSTGRES SERVER
  database:
    image: postgres:17.0-alpine3.20
    container_name: dev-postgresql
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: transfer_money_db
      POSTGRES_LOGGING: minimal
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev-network
    deploy:
      resources:
        limits:
          cpus: "0.5"     # Limita o uso de CPU a 50%
          memory: "512M"  # Limita a memória a 512 MB

  # GERENCIADOR DE DATABASE ALTERNATIVO AO PGADMIN4
  adminer:
    image: adminer:latest
    container_name: dev-adminer
    ports:
      - "5050:8080"
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database # Define o servidor de banco de dados padrão
    networks:
      - dev-network
    deploy:
      resources:
        limits:
          cpus: "0.2"     # Limita o uso de CPU a 20% de um núcleo
          memory: "128M"  # Limita a memória a 128 MB

# VOLUMES
volumes:
  db-data:
  pgadmin-data:

# REDES
networks:
  dev-network:
    driver: bridge