services:
  # POSTGRES SERVER
  database:
    image: postgres:17.0-alpine3.20
    container_name: dev-postgresql
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: transfer_money_db
      POSTGRES_LOGGING: minimal
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev-network
    deploy:
      resources:
        limits:
          cpus: "0.5"     # Limita o uso de CPU a 50%
          memory: "512M"  # Limita a memória a 512 MB

  # PGADMIN
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: dev-pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: me@example.com
#      PGADMIN_DEFAULT_PASSWORD: senha123
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    depends_on:
#      - database
#    networks:
#      - dev-network
#    deploy:
#      resources:
#        limits:
#          cpus: "0.2"     # Limita o uso de CPU a 20% de um núcleo
#          memory: "128M"  # Limita a memória a 128 MB

# VOLUMES
volumes:
  db-data:
  pgadmin-data:

# REDES
networks:
  dev-network:
    driver: bridge