services:
  database:
    image: 'postgres:17.0-alpine3.20'
    environment:
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_DB: "transfer_money_db"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: